# Nginx pods

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: 
    app: ngchart
spec:
  selector: 
    matchLabels: 
      app: monitoring
  template: 
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: nginx-web-server
          image: nginx:latest
          ports:
            - containerPort: 80

---

# Nginx-exporter

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-exporter-deployment
  labels:
    app: ngchart
spec:
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter
          env:
            - name: 
              value:
            - name:
              value:
          ports:
            - containerPort: 9113

---

#Prometheus pods

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment 
  labels:
    app: monitoring
spec:
  selector:
    matchLabels: 
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports: 
            - containerPort: 9090


---

# #Grafana pods

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: monitoring
spec:
  selector:
    matchLabels: 
      app: monitoring
  template:
    metadata:
      labels: 
        app: monitoring
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000